name: GoLint

on:
  push:
    branches:
      - '*'

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout du code
      uses: actions/checkout@v2
      
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22.2
        
    - name: Install golint
      run: GO111MODULE=off go get golang.org/x/lint/golint
      
    - name: Run golint
      run: |
        # Exécutez golint sur tous les fichiers Go
        golint ./...
